import bcrypt from 'bcryptjs';
import crypto from 'crypto';
import shortid from 'shortid';
import thinky from '../thinky';
const { type, r } = thinky;

const Profile = thinky.createModel('profiles', {
  // Optional => not specified in bodies but generated by RethinkDB
  id: type.string().default(shortid.generate),
  accountId: type.string().required(),
  name: type.object().schema({
    first: type.string().required(),
    last: type.string().required(),
    full: type.virtual().default(function() {
      return `${this.name.first} ${this.name.last}`;
    })
  }),
  location: type.string(),
  bio: type.string(),
  avatar: type.string(),
  group: type.string(),
  createdAt: type.date().default(Date.now),
  updatedAt: Date
});

export default Profile;
